### ISSUE TITLE
Error MSB3644	

### ISSUE THREAD

**Issue by UrbanSide** [cemahseri/SteamQuery.NET#2]
Hello, i have errpr ".NETFramework,Version=v5.0" not found
How i can fix it?

**Comment by cemahseri** [comment]
Hi. You have to install .NET 5.0 in order to use this library. You can download Windows 64-bit version from [here](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.3-windows-x64-installer).
