### ISSUE TITLE
Error in ReadNullTerminatedString Method

### ISSUE THREAD

**Issue by HMBSbige** [cemahseri/SteamQuery.NET#5]
I encountered an issue with the ReadNullTerminatedString method in your code. The current implementation causes [unit tests](https://github.com/HMBSbige/A2SService/actions/runs/11579121308/job/32234579625?pr=5) to fail due to incorrect handling of byte array length when reading the null-terminated string. The method reads bytes into a buffer and does not correctly track the number of valid bytes read before converting it to a string. This results in additional null bytes being included in the string, which causes discrepancies during testing.

**Comment by cemahseri** [comment]
Hi there! Thank you for reporting and sorry for late response. Timezone mismatch. I'll be fixing it in a second.
